title: Mid-MO Amateur Radio Club
email: k0ety@arrl.net
description: >-
  The official website of the Mid-MO Amateur Radio Club (K0ETY) in Jefferson City, MO.
baseurl: "/"
url: "https://k0ety.net"
collections:
  minutes:
    output: true
    permalink: /minutes/:year/:month/:title/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  activities:
    output: true
    permalink: /activities/:slug/
  operating:
    output: true
    permalink: /operating/:slug/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
